// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Tests.BDD.Features.OrdemServico
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriarOrdemDeServicoCompletaFeature : object, global::Xunit.IClassFixture<CriarOrdemDeServicoCompletaFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "BDD/Features/OrdemServico", "Criar ordem de serviço completa", "    Como administrador do sistema\r\n    Eu quero criar uma ordem de serviço comple" +
                "ta incluindo cliente, veículo, serviços e itens\r\n    Para facilitar o cadastro i" +
                "nicial de novas ordens de serviço", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CriarOrdemServicoCompleta.feature"
#line hidden
        
        public CriarOrdemDeServicoCompletaFeature(CriarOrdemDeServicoCompletaFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("BDD/Features/OrdemServico/CriarOrdemServicoCompleta.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar ordem de serviço com cliente e veículo novos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar ordem de serviço completa")]
        [global::Xunit.TraitAttribute("Description", "Registrar ordem de serviço com cliente e veículo novos")]
        public async global::System.Threading.Tasks.Task RegistrarOrdemDeServicoComClienteEVeiculoNovos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar ordem de serviço com cliente e veículo novos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("que sou um administrador autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que o cliente informado ainda não possui cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que o veículo informado ainda não possui cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("que o sistema deve cadastrar o novo cliente automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("que o sistema deve cadastrar o novo veículo automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
    await testRunner.WhenAsync("eu solicitar a criação da ordem de serviço completa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("a ordem de serviço deve ser registrada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("o sistema deve informar onde acessar a ordem criada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.AndAsync("o status inicial deve ser \"Recebida\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 18
    await testRunner.AndAsync("um código identificador deve ser gerado com prefixo \"OS-\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 19
    await testRunner.AndAsync("a ordem de serviço deve estar registrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Negar criação quando o solicitante não é administrador")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar ordem de serviço completa")]
        [global::Xunit.TraitAttribute("Description", "Negar criação quando o solicitante não é administrador")]
        public async global::System.Threading.Tasks.Task NegarCriacaoQuandoOSolicitanteNaoEAdministrador()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Negar criação quando o solicitante não é administrador", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("que sou um cliente comum autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 23
    await testRunner.WhenAsync("eu solicitar a criação da ordem de serviço completa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
    await testRunner.ThenAsync("o acesso deve ser negado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 25
    await testRunner.AndAsync("o sistema deve informar que apenas administradores podem criar ordens de serviço " +
                        "completas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Reaproveitar cadastro de cliente e veículo já existentes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar ordem de serviço completa")]
        [global::Xunit.TraitAttribute("Description", "Reaproveitar cadastro de cliente e veículo já existentes")]
        public async global::System.Threading.Tasks.Task ReaproveitarCadastroDeClienteEVeiculoJaExistentes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reaproveitar cadastro de cliente e veículo já existentes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("que sou um administrador autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 29
    await testRunner.AndAsync("que o cliente informado já possui cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 30
    await testRunner.AndAsync("que o veículo informado já possui cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 31
    await testRunner.AndAsync("que o sistema não deve duplicar o cadastro do cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.AndAsync("que o sistema não deve duplicar o cadastro do veículo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 33
    await testRunner.WhenAsync("eu solicitar a criação da ordem de serviço completa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("a ordem de serviço deve ser registrada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 35
    await testRunner.AndAsync("a ordem de serviço deve estar registrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Incluir apenas serviços e itens válidos na ordem de serviço")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar ordem de serviço completa")]
        [global::Xunit.TraitAttribute("Description", "Incluir apenas serviços e itens válidos na ordem de serviço")]
        public async global::System.Threading.Tasks.Task IncluirApenasServicosEItensValidosNaOrdemDeServico()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Incluir apenas serviços e itens válidos na ordem de serviço", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("que sou um administrador autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 39
    await testRunner.AndAsync("que o cliente e o veículo já possuem cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 40
    await testRunner.AndAsync("que informei 2 serviços mas apenas 1 existe no catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 41
    await testRunner.AndAsync("que informei 2 itens de estoque mas apenas 1 existe no estoque", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 42
    await testRunner.WhenAsync("eu solicitar a criação da ordem de serviço completa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("a ordem de serviço deve ser registrada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("apenas os serviços válidos devem ser incluídos na ordem", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 45
    await testRunner.AndAsync("apenas os itens válidos devem ser incluídos na ordem", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CriarOrdemDeServicoCompletaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CriarOrdemDeServicoCompletaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
